# Generated by Django 6.0.4 on 2026-04-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('amount', models.FloatField()),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
    ]
