# Generated by Django 6.0.4 on 2026-05-05 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='user_name',
        ),
    ]
